project:
  type: website
  output-dir: docs

website:
  title: "Tyler Celotta"
  search: false
  open-graph: true
  page-footer:
    center: "Tyler Celotta · Portland, OR · [tylercelotta@reed.edu](mailto:tylercelotta@reed.edu)"
  navbar:
    right:
      - text: Home
        href: Homepage.qmd
      - text: Portfolio
        href: Portfolio.qmd
      - text: Photography
        href: Photography.qmd
      - text: Blog
        href: Blog.qmd
    tools:
      - icon: github
        text: GitHub
        href: https://github.com/TyGuy-5
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/tyler-celotta

format:
  html:
    respect-user-color-scheme: true
    theme:
      light:  [flatly,  styles.scss]
      dark:   [darkly,  styles.scss]
    smooth-scroll: true
    page-layout: article
    toc: false