---
title: "Scout achieves Eagle status with Circle Pines library project"
format: html
---
### Names in the News
##### Feb 6, 2024 Updated Feb 8, 2024
Feb 6, 2024 Updated Feb 8, 2024

Tyler Celotta, a senior at Centennial High School, has achieved the rank of Eagle Scout. He joined Boy Scouts when he was in second grade and steadily progressed through the ranks, earning 23 merit badges, and serving as a senior patrol leader and junior assistant Scoutmaster. 
For his Eagle Scout Project, Celotta combined his interests in engineering, reading and serving the community. He constructed and installed four “Little Free Libraries” in parks around his hometown of Circle Pines. He built the prototype unit mostly independently, and once he decided on the final design, he led other Scouts through the building and installation of the libraries. Celotta worked with the city of Circle Pines to identify good locations for the libraries. 
Outside of Scouting, Celotta participates in high school sports including cross-country (captain 2023), boys swim and dive (captain 2022 and 2023), and track and field. He also participates in the National Honor Society, peer leaders, the Golden Lake mentoring program, Student Council, Student Action Leadership Team for church, and was an actor in last year’s Arrive Alive mock crash simulation. In his sparse free time. 

