---
title: "Articles Mentioning My Swimming Career"
format: html
---
### 2nd Place and New School Record
##### Head Coach Pete Crawford Feb 24, 2024

<p>30 top times of all time, a new school record, 4 entries to the state meet were accomplished by the 2024 section team. What an incredible 3 days and I couldn't be more proud to be the coach for this team. It all started with the 200 medley relay swimming to a 2nd place finish to punched their ticket to next weeks state meet. Caleb Cregan led off with a fantastic backstroke leg giving way to Benno Schuhbauer swimming the breaststroke then Tyler Celotta the butterfly, and Joe Murray follwed that up with blistering 50 freestyle. 2 events later Caleb Cregan swam to a 2nd place finish in the 200 IM with a time of 2:02.38 and Benno Schuhbauer finished 4th. Then in the next event Joe Murray punched his own ticket to state with a 2nd place finish in the 50 Free with a time of 22.20 and Manny Poscher finished 8th. 0.05 was the difference for the 200 freestyle team of Joe, Sawyer Celotta, Talen Greeson-Stormoen, and Manny Poscher from their state appearance with a 3rd place finish. But in the next event the fireworks went off for Centennial as Caleb swam to a new school record and became a section champion with a 1st place time of 53.54. Benno Schuhbauer place 3rd, Grant Page placed 6th and Jaden Lynch-Rygh took 9th.</p>

<p>At the conclusion of the meet the team earned a 2nd place finish behind Duluth for the 2nd year in a row.</p>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>Duluth</td><td>502</td></tr>
    <tr><td>2</td><td>Centennial</td><td>339</td></tr>
    <tr><td>3</td><td>Forest Lake</td><td>257</td></tr>
    <tr><td>4</td><td>Coon Rapids</td><td>240.5</td></tr>
    <tr><td>5</td><td>Andover</td><td>237</td></tr>
    <tr><td>6</td><td>Anoka</td><td>214.5</td></tr>
    <tr><td>7</td><td>Blaine</td><td>187</td></tr>
    <tr><td>8</td><td>Cambridge Isanti</td><td>126</td></tr>
  </tbody>
</table>

### Centennial Outperforms Coon Rapids in Eight Events
##### Coach Kevin Setterholm Jan 18, 2024

<p>Prior to the meet with Coon Rapids, Head Coach Pete Crawford told his swimmers that “competing against Coon Rapids allows me to put together a line-up that will give you the opportunity to swim events that you are not use too.  It gives both me as a coach and you as athletes the chance to discover new talents and abilities that the team has.”</p>

<p>Despite swimming line-up that was different from the ones used in the past two meets, the Cougars dominated the Cardinals in eight of the twelve events and more importantly for Coach Pete, he learned that many members of the team are able to preform at high levels in events that they have not swam in past meets. </p>

<p>Centennial pretty much had its victory over the Coon Rapids wrapped up by the 200 Freestyle Relay when Manny Poscher, Caleb Cregan, and Talen Greeson-Stromen swam to a first place finish and Sawyer Celotta, Gavin Manthei, Tyler Celotta and Jacob Digre took the second spot.  The win over the Cardinals was finalized though after Benno Schubauer led Jaedyn Lynch-Rygh, and Alex Larkin to the top three spots in the 100 Backstroke. </p> 

<p>Other first place finishes turned in by Centennial were by Caleb Cregan in the 200 Freestyle, Manny Poscher in the 50 freestyle, Talen  Greeson-Stromen in the 500 Freestyle, Matthew Kufner in the 100 Breaststroke and Manny Poscher, Joesph Murray, Benno Schubauer and Issac Nguyen in the 400 Freestyle Relay. </p>

<p>The fantastice swims and dives performed by the team's first and second year athletes also pleased Centennial's coaching staff and motivated Assistant Coach Kevin Setterholm to state that he was "looking forward to Saturday's seventh, eighth and ninth grade Red, White and Blue Inviational at Northdale Pool where he believes that younger Cougars will be able to shine."  </p>


### Murray Leads Centennial to a Third Place Finish at The Section 7AA True Team Meet
##### Coach Kevin Setterholm Jan 13, 2024

<p>For the second year in a row Centennial placed third, after Duluth and Andover, in the eight team Section 7AA True Team Meet on January 13, 2024.  Junior Joe Murray brought home the Cougars only first place finish by swimming a personal best time of 23.48 in the 50 Freestyle.  Centennial’s highest scoring event though was the 100 Backstroke where Junior Caleb Creagan took home a second place medal, Freshman Benno Schuhbauaer captured a fourth place medal and Freshman Grant Page earned a sixth place medal.</p>

<p>Medals were also won by Cougars in the 200 Medley Relay -  Caleb Cregan, Benno Schuhbauer, Tyler Celotta, Joseph Murray (2nd place) and Isaac Nguyen, Sawyer Celotta, Alex Larkin, Manny Poscher (5th place); in the 200 Freestyle - Benno Schubauer (5th place); in the 200 IM - Caleb Cregan (4th place) and Isaac Nguyen (6th place); the 50 Freestyle - Manny Poscher (5th place); the 100 Butterfly - Alex Larkin (6th place); in the 100 Freestyle - Manny Poscher (4th place) and Talen Greenson-Stormoen (7th place); in the 200 Freestyle Relay - Manny Poscher, Jacob Digre, Talen Greeson-Stormoen, Joseph Murray (4th place); and in the 400 Freestyle Relay - Caleb Cregan, Benno Schuhbauer, Talen Greeson-Stormoen, Isaac Nguyen (3rd place) .</p>

<p>Head Coach Pete Crawford saw many positives in the Centennial athletes' performances.  After the meet he mentioned to his coaching staff that "this afternoon we had 44 seasonal best times and we improved from last years point total by 100 points!"  Crawford also stated that this meet is a springboard for the second half of the season and that he is excited by the continuous improvement of many of the team's swimmers.<\p>

Team rankings at the end of the meet were: 
<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>Duluth</td><td>1346.5</td></tr>
    <tr><td>2</td><td>Andover</td><td>1267</td></tr>
    <tr><td>3</td><td>Centennial Lake</td><td>1237.5</td></tr>
    <tr><td>4</td><td>Anoka</td><td>972</td></tr>
    <tr><td>5</td><td>Baline</td><td>835</td></tr>
    <tr><td>6</td><td>Forest Lake</td><td>768</td></tr>
    <tr><td>7</td><td>Coon Rapids</td><td>739</td></tr>
    <tr><td>8</td><td>Cambridge Isanti</td><td>527</td></tr>
  </tbody>
</table>

### A Sweet Win It Was
##### Coach Kevin Setterholm Jan 04, 2024

<p>Over the past few years, Andover has become one of Centennial’s closest rivals and biggest frustrations at the pool. Most of the dual meets between the two teams have gone down to the last event to determine the victor, with the Huskies frequently walking away with a close win.  The Cougars frustrations over their rivals came to an end though on January 4, 2024 with Centennial’s 102 to 82 victory over Andover.<\p>

<p>From the start of the meet to its completion, the Cougars were in control by out scoring the Huskies in 8 of 12 events.  The highlight of the victory was Centennial’s sweep of both the 100 butterfly and 100 backstroke events by placing swimmers in the top three spots.  Caleb Cregan led Alex Larkin and Tyler Celotta in the Cougar’s grand slam in the 100 fly while Benno Schuhbauer led Brennan Nielson and Jaedyn Lynch-Rygh in the Cougar's cleanup in the 100 back.  Head Coach Pete Crawford was also quick the mention that during the meet Centennial turned in 72 seasonal best times. <\p>

<p>Other Cougar first place finishes were turned in by Caleb Cregan, Benno Schuhbauer, Tyler Celotta, Joe Murray in the 200 medley relay; Isaac Nguyen in the 200 freestyle and 500 freestyle; Josephy Murray in the 50 freestyle; and Jacob Digre, Talen Greeson-Stromoen, Isaac Nguyen, Joseph Murray in the 200 freestyle relay.<\p>

<p>This memorable triumph will follow Centennial this weekend to the Border Battle Invitational in Fargo, ND and into next week with its dual meet with Maple Grove.  The hope is that the team’s January 4th, win over Andover has opened new horizons of future success.<\p> 

### After Many Close Races the Cougars Triumph Over the Bengals
##### Coach Kevin Setterholm Dec 21, 2023

<p>Centennial arrived in Blaine on December 21, 2023 ready to preform and with seventy personal best time swims at the meet’s conclusion, a performance is what the Cougars gave to the fans in the Northdale pool stands.<\p> 

<p>The Cougars solid team depth really showed in its match up with Blaine.  In all but one varsity event, every one of the Centennial’s athletes scored points.  The result of this feat was a final meet score of Centennial 120 and Blaine 75. <\p> 

<p>After the meet, Head Coach Pete Crawford highlighted the expectational effort given by freshman Benno Schuhbaurer in the 200 IM and 100 breaststroke and sophomore Isaac Nguyen in the 100 Backstroke and 100 Butterfly.  Both athletes swam so well that North Metro TV interviewed them after the meet.  Crawford was also quick to mention that he was impressed by senior captain Tyler Celotta’s athleticism. Celotta had not practiced any diving since last season, but despite this predictament he stepped up to the challege of being entered in the 1 meter diving event and took a first place with a score of 144.4. <\p> 

<p>“The results of this meet puts the Cougars in a good spot before winter break”, Crawford stated.  He then explained that the many successful swims that Centennial had at the this meet will be built on during the next two weeks to help the Cougars prepare for its upcoming meets against Andover and Maple Grove.  "Both of these meets", Coach Pete says, "are going to be very exciting to watch".<\p> 

<p>First place finishes taken by Centennial were: <\p> 

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Swimmer(s)</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>200 Medley Relay</td><td>Isaac Nguyen, Benno Schubauer, Tyler Celotta, Talen Greenson-Stormoen</td></tr>
    <tr><td>1 Meter Diving</td><td>Tyler Celotta</td></tr>
    <tr><td>100 Butterfly</td><td>Isaac Nguyen</td></tr>
    <tr><td>500 Freestyle</td><td>Caleb Cregan</td></tr>
    <tr><td>100 Backstroke</td><td>Isaac Nguyen</td></tr>
    <tr><td>100 Breaststroke</td><td>Benno Schuhbauer</td></tr>
    <tr><td>400 Freestyle Relay</td><td>Joseph Murray, Caleb Cregan, Alex Larkin, Isaac Nguyen</td></tr>
  </tbody>
</table>

### Centennial Wins Bengal Invite
##### Head Coach Pete Crawford Dec 16, 2023

For the 1st time in program history the Centennial Boys Swim & Dive team won the Bengal Invite. It was truly a team effort which took until the last relay to pull off the victory. It was back and forth through the entire meet, which makes it more exciting for parents and fans. "It was great competition for the boys so early in the season and I think it will help them push towards their own goals for the season." says Coach Crawford. It wasn't the 1st place finishes that won it but the number of boys that earned top 16 placing in each of the events along with 2 relays that finished higher than their seed times. The cougars were able to score points in all 12 events. The highest place came from our 200 Medley Relay of Caleb Cregan, Isaac Nguyen, Tyler Celotta, and Joe Murray who placed 2nd and got the meet started off. Caleb also placed 3 in the 100 backstroke and Joe placed 4th in the 50 free. The race of the day was the 100 Free in which all 4 finished in the top 8. Joe finished in 5th, Talen Greeson-Stormoen 6th, Manny Poscher 7th, and Sawer Celotta dropped from 1:04 seed time to a 56.42 to take 8th. Benno Schuhbauer earned 2 5th place finishes in 100 butterfly and 100 backstroke. Elijah Manthei continues to climb the middle school record board in diving scoring his career best 224.20 on 11 dives and placed 9th. 

Results-
<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>Centennial</td><td>373</td></tr>
    <tr><td>2</td><td>Irondale</td><td>353</td></tr>
    <tr><td>3</td><td>Andover</td><td>315</td></tr>
    <tr><td>4</td><td>Coon Rapids</td><td>243</td></tr>
    <tr><td>5</td><td>White Bear Lake</td><td>240</td></tr>
    <tr><td>6</td><td>Blaine</td><td>232</td></tr>
    <tr><td>7</td><td>Osseo</td><td>222</td></tr>
    <tr><td>8</td><td>Champlin Park</td><td>176</td></tr>
    <tr><td>9</td><td>Forest Lake</td><td>170</td></tr>
  </tbody>
</table>


### Cougars Roar to Victory Over the Pirates
##### Coach Kevin Setterholm Dec 14, 2023

Centennial began its 2023-24 dual meet season with a 104 to 70 point win a over the Park Center.  The Cougars dominated the Pirates from the start of the meet to the end with 9 first place finishes, 6 second place finishes and 6 third places finishes. 

More important than the win and multiple first place finishes was how the Cougars looked in the water so early in the season.  Head Coach Pete Crawford stated that he was very impressed by the improvement of skills that the novice and JV swimmers displayed with only three weeks of practice.  Coach Pete was also very pleased by the the time drops that the seasoned athletes turned in since the team’s time trials, which took place only two weeks earlier.  With this fantastic start to the season, Crawford is expecting an exciting year for his Cougar swimmers.

Taking varsity firsts for Centennial were:

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Swimmer(s)</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>200 Medley Relay</td><td>Grant Page, Sawyer Celotta, Caleb Cregan, Manny Poscher</td></tr>
    <tr><td>200 Freestyle</td><td>Sawyer Celotta</td></tr>
    <tr><td>50 Freestyle</td><td>Manny Poscher</td></tr>
    <tr><td>100 Freestyle</td><td>Caleb Cregan</td></tr>
    <tr><td>500 Freestyle</td><td>Issac Nguyen</td></tr>
    <tr><td>200 Freestyle Relay</td><td>Jacob Digre, Tyler Celotta, Issac Nguyen, Joseph Murray</td></tr>
    <tr><td>100 Backstroke</td><td>Jaedyn Lynch-Rygh</td></tr>
    <tr><td>100 Breaststroke</td><td>Benno Schuhbauer</td></tr>
    <tr><td>400 Freestyle Relay</td><td>Isaac Nguyen, Jacob Digre, Talen Greeson-Stormoen, Joseph Murray</td></tr>
  </tbody>
</table>

### Cougars Start the Season With a Strong Performance at Conference Relays
##### Head Coach Pete Crawford Dec 09, 2023

<p>On Saturday Dec. 9 the Centennial Boys Swim and Dive team started the competitive season with a 3rd place finish the the Northwest Suburban Conference Relay meet. The cougars saw improvement from time trials in many time drops in this meet. The two meets that will be ones to watch will be Andover and Maple Grove come January. If the cougars can stay healthy there is no reason to believe this team will be one of the top teams in the 12 team conference. The cougars had 1st place finishes by;</p>

<ul>
  <li>Diving relay of Tyler Celotta, Blake Thorson, and Elijah Manthei</li>
  <li>JV 200 Medley Relay of Grant Page, Matthew Kuffner, Tyler Celotta, Jacob Digre</li>
  <li>Varsity 800 Free Relay of Garrett Clark, Isaac Nguyen, Joe, Murray, Benno Schuhbauer</li>
  <li>Varsity 400 Butterfly Relay of Benno Schuhbauer, Joe Murray, Caleb Cregan, and Isaac Nguyen</li>
</ul>

<p><strong>Final places;</strong></p>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>Maple Grove</td><td>330</td></tr>
    <tr><td>2</td><td>Andover</td><td>326</td></tr>
    <tr><td>3</td><td>Centennial</td><td>316</td></tr>
    <tr><td>4</td><td>Champlin Park</td><td>278</td></tr>
    <tr><td>5</td><td>Park Center</td><td>138</td></tr>
    <tr><td>6</td><td>Coon Rapids</td><td>132</td></tr>
  </tbody>
</table>

### The Border Battle Invitational Brings Cougar Athletes Closer Together
##### Coach Kevin Setterholm Jan 07, 2023

<p>Max Scheurer was awarded the meet's 3th top point earner for individual swimmers at the Border Battle Invitational held in Fargo, ND on January 7, 2023. Max placed first in the 100 Breaststroke and second in the 200 IM. Other Cougars that helped Centennial earn its fifth place ranking out of twelve teams were: George Atkinson, Alex Larkin, Ben Condon, Isaac Nguyen, Joesph Murray, Tyler Celotta, Manny Poscher, Garrett Clark, Benno Schubauer and Charlie Bryant.</p>

<p>After the meet, Centennial diving Coach Lee Raihle pointed out that Junior Captain Tyler Celotta had a fantastic meet by improving his personal best diving score by 58.5 points and placing eighth out of twenty divers. His new personal best score of 254.20 for 11 dives now places him as number 7 on the Centennial Swimming and Diving All Time Top 10 List.</p>

<p>During the four-hour bus ride back to Blaine, MN, Head Coach Pete Crawford told the team that this invitational was placed in the schedule as a team bonding and fun experience. He asked his athletes if this goal was met and was given an overwhelming “YES” by the swimmers. Besides the excitement of competing against North Dakota and western Minnesota athletes, the Centennial Swimming Booster Club sponsored event included travel in a coach bus, a pizza dinner and an evening at the Ninja Academy for an hour of Ninja Warrior obstacle training. Many of the team members also spiced up the overnight meet experience by plunging themselves in a bathtub full of ice and then dashing to hotel’s hot tub to regain their lost body heat. How could this not be fun!</p>

<p><strong>Team Rankings:</strong></p>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>Fargo Davies High School</td><td>329</td></tr>
    <tr><td>2</td><td>Grand Forks Knight Riders</td><td>264</td></tr>
    <tr><td>3</td><td>Sauk Rapids Rice</td><td>262</td></tr>
    <tr><td>4</td><td>Melrose/Sauk Center</td><td>212</td></tr>
    <tr><td>5</td><td>Centennial</td><td>211</td></tr>
    <tr><td>6</td><td>West Fargo Packers</td><td>211</td></tr>
    <tr><td>7</td><td>Fergus Falls</td><td>189</td></tr>
    <tr><td>8</td><td>Andover High School</td><td>179</td></tr>
    <tr><td>9</td><td>West Fargo Sheyenne</td><td>175</td></tr>
    <tr><td>10</td><td>Bemidji</td><td>110</td></tr>
    <tr><td>11</td><td>Detroit Lakes Lakers</td><td>78</td></tr>
    <tr><td>12</td><td>Morris Area / Chokio-Alberta</td><td>44</td></tr>
  </tbody>
</table>

### It Was a Nailbiter, But the Cougars Prevailed Over the Bengals
##### Coach Kevin Setterholm Dec 20, 2022

<p>Centennial was down nine swimmers due to illnesses during its December 20, 2022 meet against Blaine. Before the start of the meet, Head Coach Pete Crawford told his athletes, during his locker room talk, that Centennial's depth could possibly carry the team to victory if the boys wanted it enough. Crawford said that "with the number of absences the team had, both Blaine and Centennial will be evenly matched this evening and the team that wants it more will be the team that walks away with the win."</p>

<p>The final score of the meet was Centennial 93 and Blaine 91. It was a back-and-forth meet with many close races, but the Cougars wanted the win and with the great effort given by both the divers and the swimmers the team prevailed.</p>

<p><strong>Taking varsity first place finishes for Centennial were:</strong></p>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Swimmer(s)</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>200 Freestyle</td><td>George Atkinson</td></tr>
    <tr><td>200 IM</td><td>Isaac Nguyen</td></tr>
    <tr><td>1 Meter Diving</td><td>Tyler Celotta</td></tr>
    <tr><td>100 Freestyle</td><td>Max Scheurer</td></tr>
    <tr><td>500 Freestyle</td><td>George Atkinson</td></tr>
    <tr><td>200 Freestyle Relay</td><td>Max Scheurer, George Atkinson, Joseph Murray, Ben Condon</td></tr>
    <tr><td>100 Backstroke</td><td>Alex Larkin</td></tr>
    <tr><td>400 Freestyle Relay</td><td>Ben Condon, Alex Larkin, George Atkinson, Max Scheurer</td></tr>
  </tbody>
</table>

### Max Scheurer Destroys School Record and Heads to the State Swimming Championship Meet
##### Coach Kevin Setterholm Feb 26, 2022
<p>After Centennial’s outstanding performance at Thursday evening’s Section 7AA Prelims meet, where every Cougar swim resulted in a lifetime best performance, coaches and athletes alike were unsure if the momentum of success would continue into the Saturday, February 26, 2022 Section Finals meet. The apprehension was unwarranted as results of the meet proved that the team had what was needed to continue to improve and preform in a championship setting.</p>

<p>Max Scheurer led his teammates in the continuation of outstanding performances at the Section Finals meet where he dropped an additional .89 seconds from his previous lifetime best in the 200 IM and dropped another .27 seconds from his previous lifetime best in the 100 Breaststroke. Scheurer’s 100 Breaststroke time of :57.88 destroyed the Centennial’s breaststroke record by 2.14 seconds which was set by Brian Tran in 2018. Max will continue his season by competing in the Minnesota State Championship meet which will take place on March 4th and 5th.</p>

<p>Other personal records set by Cougar swimmers at the Sectional Finals meet were turned by George Atkinson, Max Scheurer, Quentin Lehman, Connor Herbrechtsmeyer who dropped 5.5 seconds in the 200 medley relay; Joe Murray who dropped 2.2 seconds in the 200 freestyle; Tyler Celotta who increased his score by 35 points in diving; Connor Herbrechtsmeyer who dropped .08 seconds in the 50 freestyle; Dominic Stevenson who dropped .35 seconds and Quentin Lehman who dropped 1.47 seconds in the 100 butterfly; Ben Condon who dropped .52 seconds in the 100 freestyle; Ben Condon, Quentin Lehman, Ben Loehr, Connor Herbrechtsmeyer who dropped 2.65 seconds in the 200 freestyle relay; Evan Stokkeland who dropped .27 seconds in the 100 breaststroke and Ben Loehr, Ben Condon, George Atkinson, Dominic Stevenson who dropped a whopping 7.8 seconds in the 400 freestyle relay.</p>

<p><strong>Centennial athletes who earned medals in the meet are as follows:</strong></p>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Place</th>
      <th>Swimmer(s)</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>200 Medley Relay</td><td>3rd</td><td>George Atkinson, Max Scheurer, Quentin Lehman, Connor Herbrechtsmeyer</td></tr>
    <tr><td>200 IM</td><td>4th</td><td>Max Scheurer</td></tr>
    <tr><td>50 Freestyle</td><td>7th</td><td>Connor Hebrechtsmeyer</td></tr>
    <tr><td>Diving</td><td>8th</td><td>Tyler Celotta</td></tr>
    <tr><td>100 Fly</td><td>7th</td><td>Dominic Stevenson</td></tr>
    <tr><td>100 Fly</td><td>8th</td><td>George Atkinson</td></tr>
    <tr><td>200 Freestyle Relay</td><td>4th</td><td>Ben Condon, Quentin Lehman, Ben Loehr, Connor Herbrechtsmeyer</td></tr>
    <tr><td>100 Backstroke</td><td>5th</td><td>George Atkinson</td></tr>
    <tr><td>100 Breaststroke</td><td>2nd</td><td>Max Scheurer</td></tr>
    <tr><td>400 Freestyle</td><td>7th</td><td>Ben Loehr, Ben Condon, George Atkinson, Dominic Stevenson</td></tr>
  </tbody>
</table>

<p>Special recognition is given to 7th grader Sawyer Celotta, who suffered a major back abrasion during a diving board accident at practice two days before the meet but continued to the diving finals and placed 9th overall.</p>

<p>Recognition is also given to assistant coach Kevin Setterholm who was named the 2022 Section 7AA Assistant Coach of the Year.</p>

<p><strong>Team scores at the conclusion of the meet are as follows:</strong></p>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>Duluth</td><td>515.5</td></tr>
    <tr><td>2</td><td>Anoka</td><td>362</td></tr>
    <tr><td>3</td><td>Andover</td><td>255.5</td></tr>
    <tr><td>4</td><td>Coon Rapids</td><td>234</td></tr>
    <tr><td>5</td><td>Centennial</td><td>230.5</td></tr>
    <tr><td>6</td><td>Blaine</td><td>228.5</td></tr>
    <tr><td>7</td><td>Forest Lake</td><td>185</td></tr>
    <tr><td>8</td><td>Cambridge/Isanti</td><td>91</td></tr>
  </tbody>
</table>

### The Cougars' Junior Varsity Team Dominates the Northwest Suburban Conference
##### Coach Kevin Setterholm Feb 12, 2022

<p>The Cougars dominated the Northwest Suburban Conference (West) Junior Varsity Championship meet on February 12, 2022. Team scores were:</p>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>Centennial</td><td>606</td></tr>
    <tr><td>2</td><td>Elk River</td><td>415</td></tr>
    <tr><td>3</td><td>Spring Lake Park</td><td>253</td></tr>
    <tr><td>4</td><td>Champlin Park</td><td>221</td></tr>
    <tr><td>5</td><td>Osseo</td><td>64</td></tr>
    <tr><td>6</td><td>Armstrong</td><td>0</td></tr>
  </tbody>
</table>

<p>After combining the results of Northwest Suburban Conference Championship (West) meet with "North" Championships meet, the Cougars are still the top junior varsity team in the conference. The combined meet rankings come out as follows:</p>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>Centennial</td><td>442</td></tr>
    <tr><td>2</td><td>Maple Grove</td><td>415.5</td></tr>
    <tr><td>3</td><td>Elk River</td><td>279</td></tr>
    <tr><td>4</td><td>Blaine</td><td>231</td></tr>
    <tr><td>5</td><td>Andover</td><td>222.5</td></tr>
    <tr><td>6</td><td>Anoka</td><td>188.5</td></tr>
    <tr><td>7</td><td>Spring Lake Park</td><td>188.5</td></tr>
    <tr><td>8</td><td>Champlin Park</td><td>97.5</td></tr>
    <tr><td>9</td><td>Armstrong</td><td>0</td></tr>
  </tbody>
</table>

<p>Assistant Coach Kevin Setterholm pointed out at the conclusion of the meet that 83% of the team members’ swims and dives were lifetime best performances and that the Cougars dropped a total of 275.52 seconds off the seed times that they entered the meet with. That is an average of 4 seconds dropped for each Cougar swim. Any way you look at it, Coach Kevin said, it was an extremely successful meet for Centennial.</p>

<p>Head Coach Pete Crawford was also excited with the Cougars’ meet performances. He stated that the momentum that the junior varsity team set at this championship meet will inspire Centennial’s varsity team members to perform well at their championship meet which will take place on February 24. Coach Pete also mentioned that he will be adding Talen Greeson and Jacob Digre to the Cougars’ sectional team lineup because of their outstanding performances in the 100 Breaststroke and 500 freestyle respectively.</p>

<p><strong>Taking first for Centennial in the "West" meet are as follows:</strong></p>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Swimmer(s)</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>200 Medley Relay</td><td>Garrett Clark, Benno Schuhbauer, Tyler Celotta, Jacob Taylor</td></tr>
    <tr><td>200 Freestyle</td><td>Benno Schuhbauer</td></tr>
    <tr><td>200 IM</td><td>Isaac Nguyen</td></tr>
    <tr><td>1 Meter Diving</td><td>Sawyer Celotta</td></tr>
    <tr><td>100 Butterfly</td><td>Benno Schuhbauer</td></tr>
    <tr><td>100 Freestyle</td><td>Jacob Taylor</td></tr>
    <tr><td>200 Freestyle Relay</td><td>Talen Greeson, Sawyer Celotta, Garrett Clark, Charlie Bryant</td></tr>
    <tr><td>100 Backstroke</td><td>Jacob Taylor</td></tr>
    <tr><td>400 Freestyle Relay</td><td>Jacob Taylor, Sawyer Celotta, Darick Finnerty, Benno Schuhbauer</td></tr>
  </tbody>
</table>

<p>As the season draws to a close with the Section 7AA Chapmpionship meet taking place on February 24, 25 and 26th, the Centennial Cougars' swimmers and divers expect the celebration of this season's successes to continue.</p>

### Cougars Dominate the Pirates from Start to Finish
##### Coach Kevin Setterholm Jan 21, 2021

<p>Park Center’s small swimming team allowed Centennial athletes to swim many events that they were unaccustomed to swimming at a meet.  Despite the weak line-up Coach Pete intentionally used against the Pirates, the cougars placed first in all twelve events.  The Cougars also took the second and third spots in ten of the twelve events. One of the highlights of the meet was senior swimmer, Ryan Shafer, coming out of a four-year retirement to dive in the meet, along with fellow freshman swimmer, Tyler Celotta, who debuted as a diver after learning six different dives the evening before the competition.  The most exciting event of the night was the 200 freestyle relay.  This race finished with Centennial taking the top three positions with times of 1:41.22 (Belting, Shceurer, Aardahl, Atkinson), 1:41.59 (Gulaid, Condon, Washburn, Lehman), 1:41.64 (Gillen, Herbrechtsmeyer, Loehr, Larkin).  Yes, that is only a 42 tenths of a second difference between first and second place.</p> 