---
title: "Arrive Alive"
format: html
---
### Mock crash drives home dangers of drunk, distracted driving
##### By Shannon Granholm/Managing Editor Apr 25, 2023 Updated Apr 25, 2023

<p>One student was killed, another student was paralyzed, numerous students were injured and countless lives were shattered, all because someone made a bad decision—drunk and distracted driving. 
<p>Juniors and seniors at Centennial High School (CHS) witnessed firsthand the impact their decisions can have on their peers, families and the community during Arrive Alive, a simulated fatal crash. 
<p>“Countless hours from the community have been have put into this, and this truly is a community effort to show you that the community cares for you,” said CHS Principal Tom Breuning. “We hope that the emotions here will carry with you when you are in that situation … You'll have to make a choice, do you take that drink? Do you go on that phone? What will you do in that moment?” 
<p>The Arrive Alive concept was brought to the district in 2009 by Sgt. Mark Boerboom of the Blaine Police Department, who served as the school resources officer at the time. The program is typically held every two years, but was paused during the pandemic. The last mock crash was held in 2019. 
<p>The simulation is focused on challenging teens to think about drinking, driving, personal safety and the responsibility they have to make mature decisions. It couldn’t come at a more important time — right before prom — one of the nights         Breuning says he loses sleep over. “I pray that I don't get a phone call.” 
<p>It all starts out in the morning, when the Grim Reaper and an officer visit the classrooms of the students who will be involved in the crash. The students read their obituaries, and a white rose — along with their photograph — is placed on their desks, which remain empty for the rest of the day. 
<p>Then the crash happens in the stadium. Law enforcement, firefighters, paramedics, a medical helicopter and the county coroner all respond to the scene. Paramedics treat several students for minor injuries following a head-on collision caused by a driver who was impaired and distracted by a cell phone. A seriously injured student receives medical aid and is removed from the scene by an ambulance and taken to Unity Hospital, where he is treated and determined to be paralyzed. The family of that student is present and notified by the doctor of their child’s life-altering injuries. A second student dies on scene after being thrown through a windshield and is pronounced dead and taken to the mortuary by Mueller-Bies Funeral Home. A third student is arrested for driving impaired and criminal vehicular homicide and is taken to jail.
<p>Senior Andi Koslowski acted as a backseat passenger who was drinking and smoking in the car and ends up getting a broken arm. She wanted to participate in the crash simulation to hopefully have an impact on her peers so the situation doesn’t happen to any of them. 
<p>“I know I definitely won’t ever drink and drive, and the whole texting and driving thing will affect me,” Koslowski said. Junior Tyler Celotta played the sober driver who ends up paralyzed. “I think kids don't understand how real this is and this kind of brought that to light,” Celotta said. “(I hope) they see this in their mind when they are making the decision whether or not to get in that car.” 
<p>Celotta’s mom Dayius described the experience as tough and eye-opening. The toughest part was watching her son, who is a runner, be hooked up to a bunch of machines in the hospital and talking with the doctor about how he will never be able to run again. 
<p>“It was real because they are at that age where anything can happen,” she said. “They think they are invincible. They think that it's always going happen to somebody else; they don’t think it is going to happen to them or somebody they know. Lives can change in the blink of an eye.” 
<p>She said she is hopeful Arrive Alive will make the students think twice about their choices. 
<p>“Please think before you act. Think before you drink or use drugs and then get behind the wheel to drive yourself and your friends home. Think before you get in the car with one of your friends who you know has been drinking or using drugs. Think, and then just don't get in the car. Don’t drive the car. Just don't,” said Assistant Anoka County Attorney Heather Pilon.
<p>“Some mistakes happen in a split second and they can't be undone. They are final.” 