---
title: "Centennial graduates ‘have opportunity to draw their own paths’"
format: html
---
### Graduation 2024
##### Jun 11, 2024 Updated Jun 11, 2024
##### The following four speeches were given at Centennial High School’s graduation ceremony Saturday, June 8, at Roy Wilkins Auditorium. Each year, students apply for an opportunity to speak at graduation.

### Natalie Clarys 
Hello, students, staff, family and friends. Somehow and some way, we actually made it. After 13 years of coloring books to calculus, we made it here to the final steps of our journeys. But that’s just the thing- it’s the final step and the first stride. 
In reality, this is really only the end of the very beginning in an entire lifetime of firsts and lasts, of frustrations and tears, and of laughter, joys and opportunities. And most prominently, excitement and perhaps a little bit of fear. But what are we afraid of? We’re afraid of what comes next, or rather, what doesn’t come next. We are afraid of change. Or rather, changing too much. 
When I was younger, one of my favorite books was the critically acclaimed Crocket Johnson novel, “Harold and The Purple Crayon.” Now, if you’re not familiar with this piece of novel literature, I’ll give you a brief rundown. The story centers around a 4-year-old boy who has a magical purple crayon that he uses to draw whatever he can imagine. A lasso, a cowboy or a sailboat? You betcha. This idea was essentially the best thing to me since sliced bread, as it meant that I could finally draw myself a version of Chris Hemsworth, and we could ride off into the sunset together; just he and I and a private yacht. You can imagine my horror and absolute anguish when I found out that sometimes, a crayon is just a crayon. And sometimes, we can’t expect things to be simple. 
We are not children anymore, and we might not have a purple crayon that can simply change and create whatever we wish for at a moment’s notice. However, we have ambition. We have late nights and support for one another. We have opportunity, and most importantly, we have the will to do what we so desire. That is, if we choose to take the jump and explore what is frightening. If we choose to change. 
Because, friends, you do not have a purple crayon, but you do have something that is much more powerful, which is one simple word: “yes.” Of course, I am not implying saying yes to everything, especially things that might be illegal or dangerous. But if you don’t say yes to opportunity, then you’ll never know the outcome. Say yes to discomfort and the probability that things may not always go as planned. And yes, while falling may sting, and you may be afraid to try, try again, sitting still and tapping your foot, waiting for an opportunity to arise with no sort of reaching will just leave your hands empty. So, you need to take your crayon and draw an outline. 
We have this amazing opportunity to draw our own paths if we choose to use it. But if we don’t, then we can’t. So, we keep moving forward and accept every obstacle and success that might fall in our path. And if you don’t like that path that you’re traveling down, then draw a new one. 
At the end of our paths, lies a choice. You can either move forward or stay standing, but you have the amazing opportunity to always move forward, even if you choose to stop and rest. The path will still be there, awaiting your arrival, and waiting for your next jump. You never know what beauty you’re capable of. Good luck, and Godspeed. 
 

### Gurleen Khosa 
Satriakal Saryanu, Good afternoon Class of 2024. After years of hard work and dedication, we finally made it. I’m sure many of us sitting here have been asked, “What are you going to do next?” but I would like to ask you, “Who are you going to be moving forward?” 
As we sit here today, I look around and see a class rich in diversity. Each one of us brings a unique background, a different story, and our own set of experiences that have shaped us into who we are. Moving forward, we carry these experiences with us as core memories that will last a lifetime. 
Late nights in the student section, on the field, in the band, and many early mornings at school has gotten us here today. None of this could have been possible without the help and guidance of our amazing staff, students, guardians, and loved ones. The power of the Centennial community is truly remarkable. Our supportive educators have inspired us to strive for excellence, leaving a lasting impact on all of us and our identities. 
For me, my family’s Punjabi culture has been a cornerstone of my identity. Today, as we celebrate our accomplishments, I am filled with pride not just for myself, but for all of us because our journey wasn’t without its challenges. 
Moving forward from 8th grade, the COVID-19 pandemic shut down our schools, forcing us to go online and navigate the end of middle school and beginning of high school during unprecedented times. Yet we adapted, we persevered, and we emerged stronger. 
So, some of us have our next plans figured out, and that’s amazing. And some of us don’t, and that’s okay too. That just means that not all of us have an answer to the question of what we are going to do. 
Yet we all have the opportunity to decide who we are going to be when we leave this place today. Your roles in life are going to change, but you are so much more than your role. Moving forward, I encourage you to focus on who you are beyond these roles. 
In the beginning of high school, I really cared about how I was perceived externally. I measured my worth by the number of clubs I was in, how good my hair looked, or what outfit I was wearing. As I have gotten older, I made a resolution to rebuild my identity. Moving forward, I decided that in order to heal the way I saw myself, I had to start with the way I saw and spoke about others. I began to describe people not by what they do but who they are. For example, instead of describing my twin brother as the robotics president or tuba player, I would first tell you he is kind, compassionate, and confident. I also encourage you, moving forward, not to see individuals for what they do but who they really are. 
If there is one thing I could leave you with today, it is a phrase my grandmother often tells me: “Sabar Rakh,” which means “have patience.” Dear Class of 2024, moving forward, I encourage you to choose a positive attitude, treat others with genuine kindness, and appreciate your own unique inner beauty. Life will undoubtedly present us with unexpected challenges. There will be moments of uncertainty and times when things don’t go as planned. But remember, it’s not the obstacles we face that define us, but how we respond to them. So, move forward with resilience, have patience, and remember life is about who you are, not what you are. I am so proud of each and every one of you for being here today. Roll Cougs!
 

### Tyler Celotta 
Hi Mom! Good afternoon, faculty, family, friends, and fellow graduates. I must admit, it’s both an honor and a bit nerve-wracking to stand before such a significant audience today. I could be speaking in front of the next Steve Jobs, Muhammad Ali, or even a future George Washington. But my advice; if you aspire to be the latter, please, please lose the powder wig. 
When I was younger, I met a kid on the first day of second grade. We hit it off right away—at least I think we did. It was 10 years ago, so forgive me if the details are fuzzy. Over time, he went from being my classmate to a great friend. We played in the woods and climbed trees higher than my mom would have been comfortable with had she known. His favorite color was orange, so mine became orange. I joined the Boy Scouts, so he joined the Boy Scouts. We were incredibly close. 
As we grew, we changed—not just in height or weird smells, but also in our interests and habits. We discovered who we truly were, and much to my chagrin, we drifted apart. I had conversations with many classmates and shared lunch with different kids, yet that unique bond I once held remained out of reach. A part of me wanted to go back to the way things were. However, the best thing I did for myself was to let go. I never forgot the past, but I moved on looking for something new, not an exact replacement. I opened myself up to new people and eventually made new friends. It was only after letting go of what was, that I met my best friend. 
High school is a unique place where friendships are strengthened, boundaries are tested, 
and personalities are molded. Exiting high school, we are like artists standing before a blank canvas, equipped with the skills and creativity to paint our unique masterpiece in the mosaic of the future. While some of us may pursue paths of doctors and engineers, others will venture into mechanics and plumbing, and for those who have mastered the art of staying awake in history class, well, the world awaits your expertise in ... something (clearly not my forte). 
In all seriousness, never forget what you have accomplished here and the life lessons you’ve learned. Open yourself up to new people and new experiences. While you may want to avoid water that appears to be from the east wing, remember that high school is just the starting point of your lifelong journey. 
Accept what is, let go of what was, and believe in what will be. Please hear that. 
Accept what is, let go of what was, believe in what will be, and I wish you all an incredibly bright future. 
 

### Ilham Mohamed
Dear fellow graduates of the class of 2024. We made it. Today marks a significant milestone in our lives, a moment where our hard work, dedication, and perseverance are celebrated. We have shared countless memories, grown together, and faced numerous challenges. As we stand on the cusps of new beginnings, it is with immense pride and gratitude that I address you all.
Unlike many of you sitting in front of me, I did not start my education in the Centennial district, but I am beyond happy that I finished it with all of you. My three years at Centennial High School have been some of the most exciting and spirited of my entire academic career. It is all because of how vibrant this class is. Speaking in front of you all, I want to highlight the good of our community but also address the changes we need to make to better support future classes for success.
Attending a predominantly white school as a Muslim woman of color has taught me many things. We always hear about these prejudiced people and how they treat those they view as different. To them, being different is bad. In my sophomore year at Centennial, which was also my first year here, I encountered one of these prejudiced people. I was openly ridiculed, harassed as well as verbally attacked. Being a new student at Centennial led to me being unable to get the support I needed from an adult, faculty, or admin. So, I turned to my friends. While I did find my support teachers, having that immediate aid from my friends ultimately pushed me to a realization: If I had faced this treatment, many others before and many after me would have faced the same thing. This life-altering event had settled like sand in the ocean and that disturbed us.
So, I and other students of color took this new fiery passion and channeled it towards making a difference in our district. We joined clubs, advocated for students to admin, and helped with projects to support our classmates. Two years later, I can confidently stand up here, delivering this speech because we fostered an environment where I feel comfortable being myself. I found the courage to talk about the good and the bad because we changed what Centennial used to be. We did that ourselves. That is an outstanding accomplishment in itself.
Looking at all of your faces from here, I see what I can describe as a safety net. Nobody understands the hardships of almost failing a class like you guys do. Nobody understands the stress of finals and college applications clashing like you guys do. Nobody understands the excitement of going to state finals for football and winning the title of state championships like you guys do. That ring was destined to be ours as is our bright and promising future. I find safety in knowing that my hardest high school moments are shared by every single one of you.
As we leave this ceremony as intelligent young adults, let’s strive to be the difference we want to see in our upcoming environments. Let us embrace the challenges ahead with courage, pursue our passions with relentless determination, and make a positive impact on the world. Congratulations to the class of 2024–our journey has just begun.
